### ISSUE TITLE
Does the plugin work on all pages?

### ISSUE THREAD

**Issue by Heyula** [liomj/XOOPS-Smarty-Plugin#1]
Hi @liomj 

First of all, many thanks for this great plugin. 

My problem is

The plugin pulls all the data while on the home page. But the data is not displayed in the module or in a different page. 

**Home Example :**
https://demo.erenyumak.com/
![Screenshot_1](https://user-images.githubusercontent.com/5504159/153710994-34ffbfe0-3aa2-4c8d-b349-5bd0c1926cf2.png)

**Module Page**
https://demo.erenyumak.com/modules/publisher/
![Screenshot_2](https://user-images.githubusercontent.com/5504159/153711049-444ed996-138b-4aa5-81eb-622fff92cbf8.png)

**Comment by liomj** [comment]
Hi Heyula, with my limited knowledge, im not quite sure why it does not work..maybe @mambax7 can take a look

**Comment by geekwright** [comment]
It works inside modules here. I tested it in a module template most of the time while I worked on it.

Is there anyway that the xoStats function is not called. The smarty debug night be of some help to verify that the template that contains <{xoStats}> is really included.

Can you test with the updated version that was just merged into core? The names have changed and will need adjusted in the templates.

I do want to make sure this is fixed.

**Comment by Heyula** [comment]
Hi:
Plugin now works on all pages.
Thanks

![a1](https://user-images.githubusercontent.com/5504159/161337929-328263f8-fef8-4241-b97c-3e26794e1a4e.jpg)


**Demo:**

**Home Page:**
https://demo.erenyumak.com/

**Forum Page:**
https://demo.erenyumak.com/modules/newbb/index.php

**Comment by geekwright** [comment]
Awesome! Thanks!
